Added content in files
nitibilkhu/GitAssignment02 pull request #1
Opened 2023-02-14 20:51 UTC by nitibilkhu

Add Header and footer in all files

2023-02-14 20:55 UTC, nitibilkhu commented on main.css
> +  color: yellow;
Change color white to red

2023-02-14 20:55 UTC, nitibilkhu commented on main.css
>  p {
Add more styling to css file

2023-02-14 20:55 UTC, nitibilkhu commented on index.js
>  document.get("Hello World to js Programming");
Add 2 more document.get("");

2023-02-16 09:33 UTC, nitika807 commented on index.html
> +Hello world to HTML
Can you add some description of the provided headings.

2023-02-16 09:37 UTC, nitika807 requested changes
I have added some requests in the code. Please look into this if those can be catered to ?

2023-02-16 09:37 UTC, nitika807 commented on main.css
>  h1 {
Can you define some style for other headings ?

2023-02-17 06:15 UTC, merged